name = input("Type in an name: ")
places = input(" Type in an places: ")
nouns = input("Type in an nouns: ")
verbs = input("Type in an verbs: ")
abjective = input("Type in an abjective: ")
pronouns = input("Tyoe in an pronouns: ")
country = input("Type in an country: ")
animals = input("Type in an animals: ")
Food = input("Tyoe in an Food: ")
print("Last summer, my mom and dad took me and %s on a trip to %s." % (name, places))
print("The weather there is very %s!" % abjective)
print("Northern %s has many %s and they make %s, %s there." % (country, animals, abjective, Food))
print("Many people also go to %s or see the %s." % (places, pronouns))
print("The people that live there love to eat %s and are very proud of their big %s." % (Food, nouns))
print("They also like to %s in the sun and swim in the %s! It was a really %s trip!" % (verbs, places, abjective))

